### ISSUE TITLE
Make a mod that adds electric crowbar

### ISSUE THREAD

**Issue by liach** [Railcraft/RailcraftPatronServer#10]
I think we can add an electric version of crowbar for ic2 on the server.

**Comment by Forecaster** [comment]
An electric crowbar makes no sense whatsoever.

**Comment by liach** [comment]
Why? Electricity just provides for durability.

**Comment by LizzyTrickster** [comment]
That just seems like a stupid adition to a crowbar

Screwdrivers/wrenches make sense, a crowbar does not unless you want to kill the user....

**Comment by Generalcamo** [comment]
I see no reason to add this.
