### ISSUE TITLE
Empty item list for Adventurer's Backpack from forestery mod

### ISSUE THREAD

**Issue by Ashoneeplayswithballs** [Railcraft/RailcraftPatronServer#12]
The Adventurer's Backpack is a portable storage item, and behaves just like other Backpacks. It has 15 inventory slots which hold NO predefined items. Player has to manually edit the config file and place item ID's for this backpack to be useful in any way. Can be upgraded into a Woven Adventurer's Backpack.
NOTE: To change which items go into Adventurer's Backpack, locate Forestry configuration folder and edit the file backpack.conf with item ID's of your choosing.

From:  https://ftbwiki.org/Adventurer%27s_Backpack

Need to discuss and decide what we might want to go into this bag

**Comment by Forecaster** [comment]
It's not empty. It contains these items:

```

                qualitytools:emerald_amulet
                qualitytools:emerald_ring
                literalascension:climbing_rope
                ropebridge:rope
                ropebridge:ladder_builder
                ropebridge:bridge_builder
                minecraft:sign
                xreliquary:lantern_of_paranoia
                xreliquary:sojourner_staff
                xreliquary:twilight_cloak
                xreliquary:ender_staff
                xreliquary:fortune_coin
                xreliquary:midas_touchstone
                xreliquary:infernal_tear
                xreliquary:hero_medallion
                xreliquary:destruction_catalyst
                xreliquary:infernal_claws
                xreliquary:kraken_shell
                xreliquary:salamander_eye
                antiqueatlas:antiqueAtlas
```

Feel free to suggest things that are missing

**Comment by Forecaster** [comment]
Perhaps it could also contain vanilla maps, compass and bibliocraft compass?

**Comment by CovertJaguar** [comment]
Done
