### ISSUE TITLE
Mod update: WIRED

### ISSUE THREAD

**Issue by hanakocz** [Railcraft/RailcraftPatronServer#6]
1.6.2->1.6.4 versions
https://minecraft.curseforge.com/projects/wired-more-augs/files/2415682

**1.6.4**
**Fixed**
  Monster Spawns
  -  No longer attempt to give nonexistent items to Zombies or Skeletons.
  Loot Tables
  -  Redid Power Bar and Energy Drink checks for loot generation.

**1.6.3**
**Changed**
  Tech-Visor
  -  Module System -  Combine a Tech Visor with a Hudjack, Lowlight Vision Module, or a Targeting Overlay to get modify its function. Modules are consumed when crafted. Replacing a Module will not return the previous. You're cramming an augment into a pair of glasses, things break.
  The One Probe
  -  The Tech-Visor is now identified by NBTTag as a Probe
 
**Fixed**
  Item Registration
  -  Client Side - No longer attempt to register color variants of items that aren't enabled

**Comment by hanakocz** [comment]
1.6.4->1.7.0 !!!ALPHA!!! - but let us have it covered
https://minecraft.curseforge.com/projects/wired-more-augs/files/2420383

This is an ALPHA release. While everything tested fine locally I was unable to do extensive testing beyond does it launch, does it not crash on a server, and did the changes work. Any ancillary changes have not been tested. 

1.7.0
**Added**
  Items
  -  Ore Surveying Module - Requires Scannable
      - Slot: Eyes
      - Requires: Hudjack or Hudlens 
      - Triggers a Scannable pulse for Ores
      - Salvaged augments can detect Common Ores
      - Manufactured augments can detect Common and Rare Ores
      - Triggers by pressing V Key, Reassignable.

**Changed**
  Config
  -  Redone Configuration File
      - Completely Redid Config.
      - I'm sorry.
      - You are now able to tweak spawn chances for equipment as well as drop chances
      - You can also disable certain items from Dropping as Chest loot without disabling the item completely.
      - Cybor Food stats can now be configured
      -  Essence has been replaced with the now correct term of Tolerance

  - Translation
      -  en_FR
  - Mobs
      -  Cyberskeletons
         -  Should now properly spawn with Weapons and Shields

**Comment by Forecaster** [comment]
Done. Also added Scannable.
